<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-V52KHLDN" failures="1" tests="7" name="tests.DashboardTest" time="3.237" errors="0" timestamp="2025-01-23T16:31:17 IST" skipped="0">
  <testcase classname="tests.DashboardTest" name="verifyDashboardHeader" time="0.442"/>
  <testcase classname="tests.DashboardTest" name="clickProfileDropDownMethod" time="2.224"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem1" time="0.042"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem2" time="0.040"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem3" time="0.166"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem4" time="0.145"/>
  <testcase classname="tests.DashboardTest" name="verifyDropdownItem4Er" time="0.178">
    <failure message="Item4 mismatch expected [Logoutss] but found [Logout]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Item4 mismatch expected [Logoutss] but found [Logout]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at tests.DashboardTest.verifyDropdownItem4Er(DashboardTest.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- verifyDropdownItem4Er -->
</testsuite> <!-- tests.DashboardTest -->
